baseURL = "https://sad-perlman-53b3fd.netlify.app"
googleAnalytics = ""
theme = "VARS2021"
title = "VARS2021"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "speakers"
name = "Speakers"
pre = ""
weight = "4"
[[menu.main]]
URL = "mission"
name = "About"
pre = "#"
weight = 1
[[menu.main]]
URL = "products"
name = "Topics"
pre = "#"
weight = 2
[[menu.main]]
URL = "career"
name = "Organizers"
pre = ""
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
pre = "#"
weight = 4
[params]
author = "Themefisher"
contact_info = "1001 Brickell bay <br>Dr. Miami, <br>FL 33131"
description = "This is meta description"
logo = ""
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
[[params.social]]
icon = "fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "#"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "fa-github"
link = "#"
title = "github"
[[params.social]]
icon = "fa-linkedin"
link = "#"
title = "linkedin"
